apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-server
  namespace: cerberus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-server
  template:
    metadata:
      labels:
        app: media-server
    spec:
      containers:
        - name: media-server
          image: media-server:latest
          env:
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 20000
              hostPort: 20000
              protocol: UDP
            - containerPort: 20020
              hostPort: 20020
              protocol: UDP
          volumeMounts:
            - name: shared-storage
              mountPath: /app/storage
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: media-shared-storage
