apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: media-server-ingress
  namespace: cerberus
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01   # Update to match your ClusterIssuer
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - media.glaux-serverus.eu
      secretName: media-server-tls
  rules:
    - host: media.glaux-serverus.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: media-server
                port:
                  number: 80
