apiVersion: v1
kind: Service
metadata:
  name: media-server
spec:
  type: NodePort
  selector:
    app: media-server
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
