apiVersion: v1
kind: Service
metadata:
  name: media-server
  namespace: cerberus
spec:
  type: NodePort
  selector:
    app: media-server
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP