services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: cerberus
      POSTGRES_PASSWORD: cerberus
      POSTGRES_DB: cerberus
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "6543:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    environment:
        KEYCLOAK_ADMIN: cerberus
        KEYCLOAK_ADMIN_PASSWORD: cerberus
        DB_VENDOR: postgres
        DB_ADDR: postgres
        DB_PORT: 5432
        DB_DATABASE: cerberus
        DB_USER: cerberus
        DB_PASSWORD: cerberus
        KEYCLOAK_HTTPS_PORT: 8443
        KEYCLOAK_HTTPS_KEYSTORE_FILE: /opt/jboss/keycloak/standalone/configuration/certs/keycloak.jks
        KEYCLOAK_HTTPS_KEYSTORE_PASSWORD: password
        KEYCLOAK_IMPORT: /opt/keycloak/data/import/cerberus-realm.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8443:8443"
      - "8888:8080"
    volumes:
      - certs_volume:/opt/jboss/keycloak/standalone/configuration/certs
      - keycloak_volume:/opt/keycloak/data/import/
    command:
      - "start-dev"
    depends_on:
      - postgres
    links:
      - postgres
  cerberus-back:
    build:
      context: .
      dockerfile: src/hosts/CerberusApi/Dockerfile
      args:
        - BUILD_CONFIGURATION=${BUILD_CONFIGURATION:-Release}
    ports:
      - "5222:8080"
    environment:
      Backends__PostgresQL__Marten: "Host=postgres;Port=5432;Database=cerberus;Username=cerberus;Password=cerberus;Application Name=Cerberus Back Office;Pooling=true;Minimum Pool Size=5;Maximum Pool Size=9;Keepalive=30;"
      Backends__PostgresQL__Quartz: "Host=postgres;Port=5432;Database=cerberus;Username=cerberus;Password=cerberus;Application Name=Cerberus Back Office Quartz;Pooling=true;Minimum Pool Size=5;Maximum Pool Size=9;Keepalive=30;"
      SnaphotCaptures__FolderRoot: "/app/Snapshots"
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - snapshots_volume:/app/Snapshots
volumes:
  snapshots_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./Snapshots
  certs_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./certs
  keycloak_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./keycloak