services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: cerberus
      POSTGRES_PASSWORD: cerberus
      POSTGRES_DB: cerberus
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    ports:
      - "7654:5432"
  cerberus-back:
    build:
      context: .
      dockerfile: src/hosts/CerberusApi/Dockerfile
      args:
        - BUILD_CONFIGURATION=${BUILD_CONFIGURATION:-Release}
    ports:
      - "5222:8080"
    environment:
      Backends__PostgresQL__Marten: "Host=postgres;Port=5432;Database=cerberus;Username=cerberus;Password=cerberus;Application Name=Cerberus Back Office;Pooling=true;Minimum Pool Size=5;Maximum Pool Size=9;Keepalive=30;"
      Backends__PostgresQL__Quartz: "Host=postgres;Port=5432;Database=cerberus;Username=cerberus;Password=cerberus;Application Name=Cerberus Back Office Quartz;Pooling=true;Minimum Pool Size=5;Maximum Pool Size=9;Keepalive=30;"
      SnaphotCaptures__FolderRoot: "/app/Snapshots"
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - snapshots_volume:/app/Snapshots
  cerberus-ui:
    build:
      context: .
      dockerfile: src/hosts/CerberusUI/Dockerfile
      args:
        - BUILD_CONFIGURATION=${BUILD_CONFIGURATION:- Release}
    ports:
      - "666:8080"
    environment:
      Backend__Url: "http://cerberus-back:8080/api"
      SnaphotCaptures__FolderRoot: "/app/Snapshots"

    depends_on:
      - cerberus-back
    volumes:
      - snapshots_volume:/app/Snapshots
volumes:
  snapshots_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./Snapshots