apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: cerberus-dev
build:
  local:
    push: false
  artifacts:
    - image: cerberus-api
      context: .
      docker:
        dockerfile: src/hosts/CerberusApi/Dockerfile
        buildArgs:
          BUILD_CONFIGURATION: Release
    - image: media-server
      context: ./src/hosts/MediaServer
      docker:
        dockerfile: Dockerfile.deploy
    - image: cerberus-ui
      context: ./cerberus-ui
      docker:
        dockerfile: Dockerfile
        buildArgs:
          VITE_MODE: production
manifests:
  helm:
    releases:
      - name: postgres
        chartPath: k8s/charts/postgres
        valuesFiles:
          - k8s/charts/postgres/values.yaml
      - name: shared-storage
        chartPath: k8s/charts/shared-storage
      - name: certs-manager
        chartPath: k8s/charts/certs-manager
        valuesFiles:
          - k8s/charts/certs-manager/values.yaml
      - name: media-server
        chartPath: k8s/charts/media-server
        valuesFiles:
          - k8s/charts/media-server/values.yaml
      - name: keycloak
        chartPath: k8s/charts/keycloak
        valuesFiles:
          - k8s/charts/keycloak/values.yaml
      - name: cerberus-api
        chartPath: k8s/charts/cerberus-api
        valuesFiles:
          - k8s/charts/cerberus-api/values.yaml
      - name: cerberus-ui
        chartPath: k8s/charts/cerberus-ui
        valuesFiles:
          - k8s/charts/cerberus-ui/values.yaml

deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: postgres
    port: 5432
    localPort: 5432
  - resourceType: service
    resourceName: keycloak
    port: 443
    localPort: 8443
  - resourceType: service
    resourceName: cerberus-api
    port: 443
    localPort: 8444
  - resourceType: service
    resourceName: media-server
    port: 443
    localPort: 8445
  - resourceType: service
    resourceName: cerberus-ui
    port: 443
    localPort: 8446
profiles:
  - name: local
    patches:
      - op: replace
        path: /build/artifacts/2/docker/buildArgs/VITE_MODE
        value: production.local

