apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: cerberus-dev
build:
  local:
    push: false
  artifacts:
    - image: cerberus-back
      context: .
      docker:
        dockerfile: src/hosts/CerberusApi/Dockerfile
        buildArgs:
          BUILD_CONFIGURATION: Release
    - image: media-server
      context: ./src/hosts/MediaServer
      docker:
        dockerfile: Dockerfile.deploy
    - image: cerberus-ui
      context: ./cerberus-ui
      docker:
        dockerfile: Dockerfile
        buildArgs:
          VITE_MODE: production
manifests:
  kustomize:
    paths:
      - k8s/overlays/dev
deploy:
  kubectl: {}
portForward:
  - resourceType: service
    resourceName: postgres
    port: 5432
    localPort: 5432
  - resourceType: service
    resourceName: keycloak
    port: 443
    localPort: 8443
  - resourceType: service
    resourceName: cerberus-back
    port: 443
    localPort: 8444
  - resourceType: service
    resourceName: media-server
    port: 443
    localPort: 8445
  - resourceType: service
    resourceName: cerberus-ui
    port: 443
    localPort: 8446
profiles:
  - name: local
    patches:
      - op: replace
        path: /build/artifacts/2/docker/buildArgs/VITE_MODE
        value: production.local

