apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: cerberus-dev
build:
  local:
    push: false
  artifacts:
    - image: cerberus-back
      context: .
    - image: media-server
      context: .
    - image: cerberus-ui
      context: .
deploy:
  kustomize:
    paths:
      - k8s/overlays/dev
portForward:
  - resourceType: service
    resourceName: postgres
    port: 5432
    localPort: 5432
  - resourceType: service
    resourceName: keycloak
    port: 443
    localPort: 8443
  - resourceType: service
    resourceName: cerberus-back
    port: 443
    localPort: 8444
  - resourceType: service
    resourceName: media-server
    port: 443
    localPort: 8445
  - resourceType: service
    resourceName: cerberus-ui
    port: 443
    localPort: 8446