apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dpinart@uxland.cat
    privateKeySecretRef:
      name: letsencrypt-dns01
    solvers:
      - dns01:
          webhook:
            groupName: acme.instrumentaveralux.com
            solverName: ovh
            config:
              endpoint: ovh-eu
              applicationKeySecretRef:
                name: ovh-api-credentials
                key: applicationKey
              applicationSecretSecretRef:
                name: ovh-api-credentials
                key: applicationSecret
              consumerKeySecretRef:
                name: ovh-api-credentials
                key: consumerKey
