apiVersion: v1
kind: Secret
metadata:
  name: ovh-api-credentials
  namespace: cert-manager
type: Opaque
stringData:
  applicationKey: "e2a516672ef82570"
  applicationSecret: "54f665e6df3017d3d41701a99dac2445"
  consumerKey: "30ab53988705e5490438705e3718402a"
