apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: cerberus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:25.0.0
          args:
            - start
            - --http-port=8080
            - --hostname=keycloak.glaux-serverus.eu
            - --hostname-strict=false
            - --proxy=edge
            - --import-realm
          env:
            - name: KEYCLOAK_ADMIN
              value: "cerberus"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "cerberus"
            - name: KEYCLOAK_IMPORT
              value: "/opt/keycloak/data/import/cerberus-realm.json"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: realm
              mountPath: /opt/keycloak/data/import/cerberus-realm.json
              subPath: cerberus-realm.json
            - name: profile
              mountPath: /opt/keycloak/conf/user-profile.json
              subPath: user-profile.json
      volumes:
        - name: realm
          configMap:
            name: keycloak-realm
        - name: profile
          configMap:
            name: keycloak-profile
