apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  namespace: cerberus
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-dns01   # Your ClusterIssuer name
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - keycloak.glaux-serverus.eu
      secretName: keycloak-tls
  rules:
    - host: keycloak.glaux-serverus.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 80
