# This is a generated file. Not intended for manual editing.
services:
  cerberus-back:
    build:
      context: "C:\\Users\\dpina\\RiderProjects\\cerberus-2"
      dockerfile: "src/hosts/CerberusApi/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/CerberusApi.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "cerberusapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\dpina\\RiderProjects\\cerberus-2\\src\\hosts\\CerberusApi:/app:rw"
    - "C:\\Users\\dpina\\RiderProjects\\cerberus-2:/src:rw"
    - "C:\\Users\\dpina\\.nuget\\packages:/root/.nuget/packages"
    working_dir: "/app"
