apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: cerberus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi     # Adjust size as needed
