apiVersion: apps/v1
kind: Deployment
metadata:
  name: cerberus-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cerberus-ui
  template:
    metadata:
      labels:
        app: cerberus-ui
    spec:
      containers:
        - name: cerberus-ui
          image: cerberus-ui:latest
          env:
            - name: VITE_AUTH_URL
              value: "https://keycloak.local/"
            - name: VITE_AUTH_REALM
              value: "cerberus"
            - name: VITE_AUTH_CLIENT_ID
              value: "cerberus"
            - name: VITE_CERBERUS_BACKEND_URL
              value: "https://api.cerbeus.local/"
            - name: VITE_CERBERUS_STREAMING_URL
              value: "https://api.cerbeus.local/images"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: cert
              mountPath: /etc/nginx/ssl/nginx.crt
              subPath: tls.crt
            - name: cert
              mountPath: /etc/nginx/ssl/nginx.key
              subPath: tls.key
      volumes:
        - name: cert
          secret:
            secretName: cerberus-ui-tls
