apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-shared-storage
  namespace: cerberus
spec:
  accessModes:
    - ReadWriteMany   # RWX works!
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi