{{- if .Values.clusterIssuer.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
spec:
  acme:
    server: {{ .Values.clusterIssuer.acme.server }}
    email: {{ .Values.clusterIssuer.acme.email }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.acme.privateKeySecretRef }}
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: {{ .Values.clusterIssuer.acme.cloudflareApiTokenSecretName }}
              key: {{ .Values.clusterIssuer.acme.cloudflareApiTokenSecretKey }}
{{- end }}